import { Octokit } from "@octokit/rest";

function getOctokit() {
  if (!process.env.GITHUB_TOKEN) {
    throw new Error("GITHUB_TOKEN is not set");
  }
  return new Octokit({ auth: process.env.GITHUB_TOKEN });
}

const TEMPLATE_OWNER = "calverda";
const TEMPLATE_REPO = "prospect-site-template";

export async function createGitHubRepo(name: string): Promise<string> {
  const octokit = getOctokit();
  const { data } = await octokit.rest.repos.createForAuthenticatedUser({
    name,
    private: true,
    auto_init: true,
    description: "Preview site — auto-generated by Calverda Prospect Engine",
  });
  return data.clone_url!;
}

/** Create a new repo from the prospect-site-template */
export async function createRepoFromTemplate(
  repoName: string
): Promise<{ repoUrl: string; owner: string }> {
  const octokit = getOctokit();

  try {
    const { data } = await octokit.rest.repos.createUsingTemplate({
      template_owner: TEMPLATE_OWNER,
      template_repo: TEMPLATE_REPO,
      name: repoName,
      owner: TEMPLATE_OWNER,
      private: false,
      description: "Preview site — auto-generated by Calverda Prospect Engine",
    });

    return {
      repoUrl: data.html_url,
      owner: data.owner.login,
    };
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    if (message.includes("Name already exists")) {
      console.log(`[github] Repo ${TEMPLATE_OWNER}/${repoName} already exists — reusing`);
      const { data } = await octokit.rest.repos.get({
        owner: TEMPLATE_OWNER,
        repo: repoName,
      });
      return {
        repoUrl: data.html_url,
        owner: data.owner.login,
      };
    }
    throw err;
  }
}

/**
 * Push or update a file in a repo, with retries.
 * Retries handle the case where a template repo isn't ready yet.
 */
export async function pushFileToRepo(
  owner: string,
  repo: string,
  path: string,
  content: string,
  message: string,
  maxRetries = 40,
  retryDelayMs = 3000
): Promise<void> {
  const octokit = getOctokit();

  for (let attempt = 1; attempt <= maxRetries; attempt++) {
    try {
      // Check if file already exists to get its SHA
      let sha: string | undefined;
      try {
        const { data } = await octokit.rest.repos.getContent({
          owner,
          repo,
          path,
        });
        if (!Array.isArray(data) && data.type === "file") {
          sha = data.sha;
        }
      } catch {
        // File doesn't exist yet — that's fine
      }

      await octokit.rest.repos.createOrUpdateFileContents({
        owner,
        repo,
        path,
        message,
        content: Buffer.from(content).toString("base64"),
        sha,
      });

      if (attempt > 1) {
        console.log(`[github] pushFileToRepo succeeded on attempt ${attempt}`);
      }
      return;
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      // Repo not ready yet (no branch, empty, etc.) — retry
      if (attempt < maxRetries) {
        console.log(`[github] pushFileToRepo attempt ${attempt} failed: ${msg} — retrying in ${retryDelayMs / 1000}s`);
        await new Promise((r) => setTimeout(r, retryDelayMs));
      } else {
        throw new Error(`pushFileToRepo failed after ${maxRetries} attempts: ${msg}`);
      }
    }
  }
}

export async function deleteGitHubRepo(
  owner: string,
  name: string
): Promise<void> {
  const octokit = getOctokit();
  await octokit.rest.repos.delete({ owner, repo: name });
}
