import { Octokit } from "@octokit/rest";

function getOctokit() {
  if (!process.env.GITHUB_TOKEN) {
    throw new Error("GITHUB_TOKEN is not set");
  }
  return new Octokit({ auth: process.env.GITHUB_TOKEN });
}

const TEMPLATE_OWNER = "calverda";
const TEMPLATE_REPO = "prospect-site-template";

export async function createGitHubRepo(name: string): Promise<string> {
  const octokit = getOctokit();
  const { data } = await octokit.rest.repos.createForAuthenticatedUser({
    name,
    private: true,
    auto_init: true,
    description: "Preview site — auto-generated by Calverda Prospect Engine",
  });
  return data.clone_url!;
}

/** Create a new repo from the prospect-site-template */
export async function createRepoFromTemplate(
  repoName: string
): Promise<{ repoUrl: string; owner: string }> {
  const octokit = getOctokit();

  const { data } = await octokit.rest.repos.createUsingTemplate({
    template_owner: TEMPLATE_OWNER,
    template_repo: TEMPLATE_REPO,
    name: repoName,
    owner: TEMPLATE_OWNER,
    private: false,
    description: "Preview site — auto-generated by Calverda Prospect Engine",
  });

  return {
    repoUrl: data.html_url,
    owner: data.owner.login,
  };
}

/** Push or update a file in a repo */
export async function pushFileToRepo(
  owner: string,
  repo: string,
  path: string,
  content: string,
  message: string
): Promise<void> {
  const octokit = getOctokit();

  // Check if file already exists to get its SHA
  let sha: string | undefined;
  try {
    const { data } = await octokit.rest.repos.getContent({
      owner,
      repo,
      path,
    });
    if (!Array.isArray(data) && data.type === "file") {
      sha = data.sha;
    }
  } catch {
    // File doesn't exist yet — that's fine
  }

  await octokit.rest.repos.createOrUpdateFileContents({
    owner,
    repo,
    path,
    message,
    content: Buffer.from(content).toString("base64"),
    sha,
  });
}

/** Wait for repo to be ready (template generation can take a moment) */
export async function waitForRepo(
  owner: string,
  repo: string,
  maxWaitMs = 30000
): Promise<void> {
  const octokit = getOctokit();
  const start = Date.now();

  while (Date.now() - start < maxWaitMs) {
    try {
      const { data } = await octokit.rest.repos.get({ owner, repo });
      // Template repos start empty — wait until they have content
      if (data.size > 0) return;
    } catch {
      // Repo not ready yet
    }
    await new Promise((r) => setTimeout(r, 2000));
  }

  throw new Error(`Repo ${owner}/${repo} not ready after ${maxWaitMs / 1000}s`);
}

export async function deleteGitHubRepo(
  owner: string,
  name: string
): Promise<void> {
  const octokit = getOctokit();
  await octokit.rest.repos.delete({ owner, repo: name });
}
