import type { IndustryKey } from "@/lib/pipeline/types";

export interface IndustryConfig {
  name: string;
  searchTerms: string[];
  avgTicket: { service: number; install: number };
  conversionRate: number;
  closeRate: number;
  gbpCategory: string;
  defaultServices: { name: string; icon: string; desc: string }[];
  whyChoose: { title: string; desc: string }[];
  warrantyText: string;
  badgeText: string;
  availabilityText: string;
}

export const INDUSTRIES: Record<IndustryKey, IndustryConfig> = {
  hvac: {
    name: "HVAC",
    searchTerms: [
      "hvac repair",
      "ac repair",
      "heating repair",
      "furnace repair",
      "air conditioning installation",
      "hvac service",
      "emergency hvac",
    ],
    avgTicket: { service: 350, install: 8500 },
    conversionRate: 0.12,
    closeRate: 0.45,
    gbpCategory: "HVAC contractor",
    defaultServices: [
      { name: "AC Repair & Service", icon: "❄️", desc: "Fast, reliable air conditioning repair. Same-day service available." },
      { name: "Heating System Repair", icon: "🔥", desc: "Expert furnace and heating system repair for all winter long." },
      { name: "HVAC Installation", icon: "🌬️", desc: "Professional installation of new heating and cooling systems." },
      { name: "Preventive Maintenance", icon: "📋", desc: "Regular tune-ups that extend equipment life and prevent breakdowns." },
      { name: "Ductwork Services", icon: "🔧", desc: "Duct cleaning, repair, and installation for optimal airflow." },
      { name: "Indoor Air Quality", icon: "🏠", desc: "Air purifiers, humidifiers, and filtration for healthier air." },
    ],
    whyChoose: [
      { title: "Same-Day Emergency Service", desc: "Most calls answered within 2 hours." },
      { title: "Licensed & Factory-Trained", desc: "Certified by top manufacturers with continuous training." },
      { title: "Upfront Pricing", desc: "Clear quote before any work begins, guaranteed." },
      { title: "Satisfaction Guaranteed", desc: "Not happy? We come back and make it right — free." },
    ],
    warrantyText: "1-Year Labor Warranty",
    badgeText: "24/7 Emergency Service",
    availabilityText: "Available now — same-day service",
  },

  plumbing: {
    name: "Plumbing",
    searchTerms: [
      "plumber near me",
      "emergency plumber",
      "plumbing repair",
      "drain cleaning",
      "water heater repair",
      "pipe repair",
      "sewer line repair",
    ],
    avgTicket: { service: 280, install: 4500 },
    conversionRate: 0.14,
    closeRate: 0.5,
    gbpCategory: "Plumber",
    defaultServices: [
      { name: "Emergency Repairs", icon: "🔧", desc: "Burst pipes, major leaks, and emergencies handled 24/7." },
      { name: "Drain Cleaning", icon: "🚿", desc: "Professional drain clearing for clogs and sewer backups." },
      { name: "Fixture Installation", icon: "🚰", desc: "Faucets, toilets, sinks, and tubs installed with precision." },
      { name: "Water Heater Service", icon: "🔥", desc: "Tank and tankless water heater repair and replacement." },
      { name: "Repiping & Pipe Repair", icon: "🏗️", desc: "Complete repiping and targeted repair for older homes." },
      { name: "Leak Detection", icon: "🔍", desc: "Advanced technology to find hidden leaks before they cause damage." },
    ],
    whyChoose: [
      { title: "Fast Response Times", desc: "Most calls serviced within 90 minutes." },
      { title: "Licensed Master Plumber", desc: "Every job supervised by a licensed master plumber." },
      { title: "Clean & Respectful", desc: "Shoe covers, drop cloths, thorough cleanup every time." },
      { title: "Fair, Honest Pricing", desc: "Detailed written estimates before starting. No hidden fees." },
    ],
    warrantyText: "1-Year Parts & Labor",
    badgeText: "24/7 Emergency Service",
    availabilityText: "Emergency plumber on call now",
  },

  electrician: {
    name: "Electrical",
    searchTerms: [
      "electrician near me",
      "electrical repair",
      "panel upgrade",
      "rewiring",
      "lighting installation",
      "generator installation",
      "ev charger",
    ],
    avgTicket: { service: 320, install: 6000 },
    conversionRate: 0.11,
    closeRate: 0.42,
    gbpCategory: "Electrician",
    defaultServices: [
      { name: "Electrical Repair", icon: "⚡", desc: "Troubleshooting and repair of all electrical issues." },
      { name: "Lighting Installation", icon: "💡", desc: "Interior, exterior, and landscape lighting design." },
      { name: "Panel Upgrades", icon: "🔌", desc: "Panel upgrades to handle modern power demands." },
      { name: "Whole-Home Rewiring", icon: "🏠", desc: "Complete rewiring for older homes to meet safety codes." },
      { name: "Generator Installation", icon: "🔋", desc: "Standby generator installation for uninterrupted power." },
      { name: "EV Charger Install", icon: "🛡️", desc: "Level 2 electric vehicle charger for home or business." },
    ],
    whyChoose: [
      { title: "Safety First", desc: "Every job completed to NEC code standards." },
      { title: "Master Electrician Led", desc: "Licensed master electricians on every project." },
      { title: "Transparent Quotes", desc: "Itemized quotes. The price we quote is the price you pay." },
      { title: "Lifetime Warranty", desc: "We stand behind every installation for life." },
    ],
    warrantyText: "Lifetime Workmanship Warranty",
    badgeText: "Licensed & Insured",
    availabilityText: "Same-day appointments available",
  },

  landscaping: {
    name: "Landscaping",
    searchTerms: [
      "landscaper near me",
      "lawn care",
      "landscape design",
      "tree service",
      "hardscaping",
      "sprinkler system",
      "mulching",
    ],
    avgTicket: { service: 200, install: 12000 },
    conversionRate: 0.1,
    closeRate: 0.38,
    gbpCategory: "Landscaper",
    defaultServices: [
      { name: "Lawn Maintenance", icon: "🌿", desc: "Weekly and bi-weekly mowing, edging, and trimming." },
      { name: "Landscape Design", icon: "🏡", desc: "Custom design that transforms your outdoor space." },
      { name: "Tree & Shrub Care", icon: "🌳", desc: "Pruning, trimming, removal, and health treatments." },
      { name: "Hardscaping", icon: "💎", desc: "Patios, walkways, retaining walls built to last." },
      { name: "Irrigation Systems", icon: "💧", desc: "Sprinkler design, installation, and maintenance." },
      { name: "Seasonal Cleanup", icon: "🍂", desc: "Spring/fall cleanup including leaf removal and mulching." },
    ],
    whyChoose: [
      { title: "Design + Build", desc: "One team from concept to completion." },
      { title: "Reliable & Consistent", desc: "We show up on schedule, every time." },
      { title: "Local Knowledge", desc: "We know what thrives in your climate and soil." },
      { title: "Fully Insured", desc: "Complete liability and workers' comp coverage." },
    ],
    warrantyText: "Plant Survival Guarantee",
    badgeText: "Free Design Consultation",
    availabilityText: "Scheduling for this week",
  },

  dental: {
    name: "Dental",
    searchTerms: [
      "dentist near me",
      "dental office",
      "teeth cleaning",
      "dental implants",
      "cosmetic dentist",
      "emergency dentist",
    ],
    avgTicket: { service: 250, install: 5000 },
    conversionRate: 0.08,
    closeRate: 0.55,
    gbpCategory: "Dentist",
    defaultServices: [
      { name: "General Dentistry", icon: "🦷", desc: "Exams, cleanings, fillings, and preventive care." },
      { name: "Cosmetic Dentistry", icon: "✨", desc: "Veneers, bonding, and smile makeovers." },
      { name: "Teeth Whitening", icon: "😁", desc: "Professional in-office and take-home whitening." },
      { name: "Dental Implants", icon: "🔬", desc: "Permanent tooth replacement that looks natural." },
      { name: "Pediatric Dentistry", icon: "👶", desc: "Gentle, kid-friendly care in a welcoming environment." },
      { name: "Emergency Dental", icon: "🆘", desc: "Same-day emergency appointments for dental trauma." },
    ],
    whyChoose: [
      { title: "Modern Technology", desc: "Digital x-rays, intraoral cameras, same-day crowns." },
      { title: "Gentle & Comfortable", desc: "Sedation options for anxious patients." },
      { title: "Insurance Friendly", desc: "Most major plans accepted with flexible payment." },
      { title: "Experienced Team", desc: "Decades of combined experience and advanced training." },
    ],
    warrantyText: "Satisfaction Guaranteed",
    badgeText: "Accepting New Patients",
    availabilityText: "Same-week appointments available",
  },

  behavioral_health: {
    name: "Behavioral Health",
    searchTerms: [
      "therapist near me",
      "counselor near me",
      "anxiety treatment",
      "depression therapy",
      "couples counseling",
      "mental health services",
    ],
    avgTicket: { service: 175, install: 0 },
    conversionRate: 0.09,
    closeRate: 0.6,
    gbpCategory: "Mental health service",
    defaultServices: [
      { name: "Individual Therapy", icon: "🧠", desc: "One-on-one therapy for anxiety, depression, and trauma." },
      { name: "Couples Counseling", icon: "💬", desc: "Evidence-based couples therapy approaches." },
      { name: "Family Therapy", icon: "👫", desc: "Improve communication and resolve conflicts together." },
      { name: "Group Therapy", icon: "👨‍👩‍👧", desc: "Supportive group sessions for shared experiences." },
      { name: "Stress & Anxiety", icon: "🧘", desc: "Proven techniques for managing anxiety and stress." },
      { name: "Psychiatric Evaluation", icon: "📋", desc: "Comprehensive assessments and medication management." },
    ],
    whyChoose: [
      { title: "Evidence-Based", desc: "CBT, DBT, EMDR, and other proven methods." },
      { title: "Safe Environment", desc: "Confidential, judgment-free space for healing." },
      { title: "Insurance Accepted", desc: "Most plans accepted with sliding scale options." },
      { title: "Flexible Scheduling", desc: "Evening, weekend, and telehealth available." },
    ],
    warrantyText: "Free Initial Consultation",
    badgeText: "Now Accepting Clients",
    availabilityText: "Appointments available this week",
  },

  pest_control: {
    name: "Pest Control",
    searchTerms: [
      "pest control near me",
      "exterminator near me",
      "termite treatment",
      "bed bug treatment",
      "rodent control",
      "mosquito control",
      "ant exterminator",
    ],
    avgTicket: { service: 250, install: 1800 },
    conversionRate: 0.13,
    closeRate: 0.52,
    gbpCategory: "Pest control service",
    defaultServices: [
      { name: "General Pest Control", icon: "🐜", desc: "Eliminate ants, roaches, spiders, and other common household pests." },
      { name: "Termite Treatment", icon: "🪵", desc: "Inspection, treatment, and prevention to protect your home's structure." },
      { name: "Rodent Control", icon: "🐀", desc: "Humane and effective removal of mice, rats, and other rodents." },
      { name: "Bed Bug Treatment", icon: "🛏️", desc: "Heat and chemical treatments for complete bed bug elimination." },
      { name: "Mosquito & Tick Control", icon: "🦟", desc: "Yard treatments to reclaim your outdoor living spaces." },
      { name: "Wildlife Exclusion", icon: "🦝", desc: "Seal entry points and remove unwanted wildlife safely." },
    ],
    whyChoose: [
      { title: "Same-Day Service", desc: "Emergency pest situations handled within hours." },
      { title: "Family & Pet Safe", desc: "EPA-approved treatments safe for your whole household." },
      { title: "Guaranteed Results", desc: "If pests come back between treatments, so do we — free." },
      { title: "Licensed Technicians", desc: "State-certified and continuously trained professionals." },
    ],
    warrantyText: "Pest-Free Guarantee",
    badgeText: "Free Inspection",
    availabilityText: "Same-day service available",
  },

  general_contractor: {
    name: "General Contracting",
    searchTerms: [
      "general contractor near me",
      "home remodeling",
      "kitchen renovation",
      "bathroom remodel",
      "home additions",
      "roofing contractor",
      "construction company",
    ],
    avgTicket: { service: 500, install: 35000 },
    conversionRate: 0.07,
    closeRate: 0.35,
    gbpCategory: "General contractor",
    defaultServices: [
      { name: "Kitchen Remodeling", icon: "🍳", desc: "Complete kitchen renovations from design to finish." },
      { name: "Bathroom Remodeling", icon: "🚿", desc: "Modern bathroom upgrades and full gut renovations." },
      { name: "Home Additions", icon: "🏗️", desc: "Room additions, second stories, and garage conversions." },
      { name: "Roofing", icon: "🏠", desc: "Roof replacement, repair, and new construction." },
      { name: "Basement Finishing", icon: "🔨", desc: "Transform your basement into usable living space." },
      { name: "Siding & Exteriors", icon: "🪟", desc: "Siding, windows, doors, and exterior renovations." },
    ],
    whyChoose: [
      { title: "Licensed & Insured", desc: "Fully licensed general contractor with comprehensive insurance." },
      { title: "Turnkey Projects", desc: "We manage every trade so you deal with one team." },
      { title: "Transparent Pricing", desc: "Detailed written estimates with no surprise change orders." },
      { title: "Quality Craftsmanship", desc: "Built to last with premium materials and skilled tradespeople." },
    ],
    warrantyText: "5-Year Workmanship Warranty",
    badgeText: "Free Estimates",
    availabilityText: "Scheduling consultations now",
  },

  masonry: {
    name: "Masonry & Concrete",
    searchTerms: [
      "mason near me",
      "masonry contractor",
      "concrete contractor",
      "brick work",
      "stone work",
      "retaining wall contractor",
      "patio installation",
    ],
    avgTicket: { service: 400, install: 15000 },
    conversionRate: 0.08,
    closeRate: 0.38,
    gbpCategory: "Masonry contractor",
    defaultServices: [
      { name: "Brick & Block Work", icon: "🧱", desc: "Brick walls, block foundations, and structural masonry." },
      { name: "Concrete Work", icon: "🏗️", desc: "Foundations, slabs, driveways, and decorative concrete." },
      { name: "Stone Veneer & Facades", icon: "🪨", desc: "Natural and manufactured stone for walls and facades." },
      { name: "Retaining Walls", icon: "🧱", desc: "Structural and decorative retaining walls for grading." },
      { name: "Patios & Walkways", icon: "💎", desc: "Custom patios, walkways, and outdoor living spaces." },
      { name: "Chimney & Fireplace", icon: "🔥", desc: "Chimney repair, rebuilds, and fireplace construction." },
    ],
    whyChoose: [
      { title: "Master Craftsmen", desc: "Skilled masons with decades of experience." },
      { title: "Quality Materials", desc: "Premium brick, stone, and concrete for lasting results." },
      { title: "Structural Expertise", desc: "Engineered solutions for foundations and retaining walls." },
      { title: "Fully Licensed", desc: "Licensed, insured, and code-compliant on every job." },
    ],
    warrantyText: "5-Year Structural Warranty",
    badgeText: "Free Estimates",
    availabilityText: "Scheduling consultations now",
  },

  fence: {
    name: "Fencing",
    searchTerms: [
      "fence company near me",
      "fence installation",
      "vinyl fence",
      "wood fence",
      "chain link fence",
      "ornamental fence",
      "fence repair",
    ],
    avgTicket: { service: 300, install: 6000 },
    conversionRate: 0.12,
    closeRate: 0.45,
    gbpCategory: "Fence contractor",
    defaultServices: [
      { name: "Wood Fencing", icon: "🪵", desc: "Cedar, pine, and composite wood fence installation." },
      { name: "Vinyl Fencing", icon: "🏡", desc: "Low-maintenance vinyl fencing in a variety of styles." },
      { name: "Chain Link Fencing", icon: "🔗", desc: "Durable chain link for security and property lines." },
      { name: "Ornamental & Iron", icon: "🏛️", desc: "Decorative aluminum and wrought iron fencing." },
      { name: "Gate Installation", icon: "🚪", desc: "Custom gates, automated openers, and access systems." },
      { name: "Fence Repair", icon: "🔧", desc: "Storm damage repair, post replacement, and restoration." },
    ],
    whyChoose: [
      { title: "Free On-Site Estimates", desc: "We measure your property and quote on the spot." },
      { title: "Quality Materials", desc: "Premium lumber, vinyl, and metals built to last." },
      { title: "Professional Installation", desc: "Clean, efficient crews that respect your property." },
      { title: "Fully Insured", desc: "Complete liability and workers' comp coverage." },
    ],
    warrantyText: "Lifetime Vinyl Warranty",
    badgeText: "Free Estimates",
    availabilityText: "Scheduling installations this week",
  },

  solar: {
    name: "Solar",
    searchTerms: [
      "solar panel installation",
      "solar company near me",
      "solar energy",
      "solar installer",
      "residential solar",
      "solar battery storage",
      "solar roof",
    ],
    avgTicket: { service: 500, install: 28000 },
    conversionRate: 0.06,
    closeRate: 0.3,
    gbpCategory: "Solar energy contractor",
    defaultServices: [
      { name: "Solar Panel Installation", icon: "☀️", desc: "Rooftop and ground-mount solar panel systems." },
      { name: "Battery Storage", icon: "🔋", desc: "Home battery backup for energy independence." },
      { name: "System Design", icon: "📐", desc: "Custom system design optimized for your roof and usage." },
      { name: "Panel Maintenance", icon: "🔧", desc: "Cleaning, inspection, and performance optimization." },
      { name: "EV Charger Integration", icon: "🚗", desc: "Solar-powered EV charging station installation." },
      { name: "Commercial Solar", icon: "🏢", desc: "Large-scale solar for businesses and commercial properties." },
    ],
    whyChoose: [
      { title: "Certified Installers", desc: "NABCEP-certified technicians on every project." },
      { title: "Maximize Savings", desc: "Expert system sizing to maximize your energy savings." },
      { title: "Tax Credit Guidance", desc: "Help navigating federal and state solar incentives." },
      { title: "25-Year Warranty", desc: "Panel and workmanship warranties for peace of mind." },
    ],
    warrantyText: "25-Year Panel Warranty",
    badgeText: "Free Solar Assessment",
    availabilityText: "Free consultations available",
  },

  pool: {
    name: "Pool Services",
    searchTerms: [
      "pool contractor near me",
      "pool installation",
      "pool repair",
      "pool maintenance",
      "inground pool",
      "pool renovation",
      "pool service",
    ],
    avgTicket: { service: 300, install: 55000 },
    conversionRate: 0.07,
    closeRate: 0.32,
    gbpCategory: "Swimming pool contractor",
    defaultServices: [
      { name: "Pool Construction", icon: "🏊", desc: "Custom inground pool design and construction." },
      { name: "Pool Renovation", icon: "🔄", desc: "Replastering, retiling, and complete pool makeovers." },
      { name: "Pool Maintenance", icon: "🧹", desc: "Weekly cleaning, chemical balancing, and equipment checks." },
      { name: "Equipment Repair", icon: "🔧", desc: "Pump, filter, heater, and automation system repair." },
      { name: "Pool Opening & Closing", icon: "📅", desc: "Seasonal opening and winterization services." },
      { name: "Spa & Hot Tub", icon: "♨️", desc: "Hot tub installation, repair, and maintenance." },
    ],
    whyChoose: [
      { title: "Licensed & Insured", desc: "Fully licensed pool contractor with comprehensive coverage." },
      { title: "Custom Designs", desc: "Unique pools tailored to your backyard and lifestyle." },
      { title: "Reliable Service", desc: "Consistent maintenance schedules you can count on." },
      { title: "Expert Technicians", desc: "Factory-trained on all major pool equipment brands." },
    ],
    warrantyText: "Lifetime Shell Warranty",
    badgeText: "Free Design Consultation",
    availabilityText: "Scheduling consultations now",
  },

  paving: {
    name: "Paving",
    searchTerms: [
      "paving contractor near me",
      "asphalt paving",
      "driveway paving",
      "parking lot paving",
      "sealcoating",
      "concrete driveway",
      "blacktop",
    ],
    avgTicket: { service: 400, install: 8000 },
    conversionRate: 0.1,
    closeRate: 0.4,
    gbpCategory: "Paving contractor",
    defaultServices: [
      { name: "Asphalt Paving", icon: "🛣️", desc: "New asphalt driveways, roads, and parking lots." },
      { name: "Sealcoating", icon: "🖌️", desc: "Protective sealcoat to extend pavement life." },
      { name: "Concrete Paving", icon: "🏗️", desc: "Concrete driveways, sidewalks, and aprons." },
      { name: "Patching & Repair", icon: "🔧", desc: "Pothole repair, crack filling, and resurfacing." },
      { name: "Parking Lots", icon: "🅿️", desc: "Commercial parking lot paving, striping, and maintenance." },
      { name: "Drainage Solutions", icon: "💧", desc: "Catch basins, French drains, and grading for proper drainage." },
    ],
    whyChoose: [
      { title: "Commercial Equipment", desc: "Full-size paving equipment for professional results." },
      { title: "Quality Materials", desc: "DOT-spec asphalt and premium concrete mixes." },
      { title: "Competitive Pricing", desc: "Fair pricing with no hidden costs or surprises." },
      { title: "Fast Turnaround", desc: "Most residential jobs completed in 1-2 days." },
    ],
    warrantyText: "2-Year Workmanship Warranty",
    badgeText: "Free Estimates",
    availabilityText: "Scheduling this week",
  },

  windows_doors: {
    name: "Windows & Doors",
    searchTerms: [
      "window replacement near me",
      "window installation",
      "door installation",
      "replacement windows",
      "entry doors",
      "sliding doors",
      "window company",
    ],
    avgTicket: { service: 350, install: 12000 },
    conversionRate: 0.09,
    closeRate: 0.38,
    gbpCategory: "Window installation service",
    defaultServices: [
      { name: "Window Replacement", icon: "🪟", desc: "Energy-efficient replacement windows for every room." },
      { name: "Entry Doors", icon: "🚪", desc: "Front door, storm door, and security door installation." },
      { name: "Sliding & Patio Doors", icon: "🏡", desc: "Sliding glass and French patio door installation." },
      { name: "Bay & Bow Windows", icon: "🏠", desc: "Custom bay and bow window design and installation." },
      { name: "Siding & Trim", icon: "🔨", desc: "Exterior trim, capping, and siding to complement new windows." },
      { name: "Energy Audits", icon: "📊", desc: "Home energy assessment to identify efficiency opportunities." },
    ],
    whyChoose: [
      { title: "Energy Savings", desc: "Energy Star rated windows that lower utility bills." },
      { title: "Expert Installation", desc: "Factory-trained installers for a perfect fit and seal." },
      { title: "Top Brands", desc: "Premium products from leading window manufacturers." },
      { title: "Lifetime Warranty", desc: "Lifetime glass breakage and product warranty." },
    ],
    warrantyText: "Lifetime Product Warranty",
    badgeText: "Free In-Home Estimate",
    availabilityText: "Free estimates available now",
  },

  church: {
    name: "Church / House of Worship",
    searchTerms: [
      "church near me",
      "churches in",
      "house of worship",
      "sunday service",
      "bible study near me",
      "youth ministry",
      "community church",
    ],
    avgTicket: { service: 0, install: 5000 },
    conversionRate: 0.06,
    closeRate: 0.3,
    gbpCategory: "Church",
    defaultServices: [
      { name: "Sunday Services", icon: "⛪", desc: "Weekly worship services for the whole family." },
      { name: "Youth Ministry", icon: "🧒", desc: "Engaging programs for children and teens." },
      { name: "Community Outreach", icon: "🤝", desc: "Serving the community through volunteer programs and events." },
      { name: "Small Groups", icon: "👥", desc: "Bible study and fellowship groups throughout the week." },
      { name: "Events & Programs", icon: "📅", desc: "Seasonal events, holiday services, and special programs." },
      { name: "Online Worship", icon: "💻", desc: "Live-streamed services for members who can't attend in person." },
    ],
    whyChoose: [
      { title: "Welcoming Community", desc: "A warm, inclusive place for everyone." },
      { title: "Strong Leadership", desc: "Dedicated pastoral team focused on spiritual growth." },
      { title: "Family-Focused", desc: "Programs for every age group and life stage." },
      { title: "Community Impact", desc: "Active in serving and supporting the local community." },
    ],
    warrantyText: "All Are Welcome",
    badgeText: "Visitors Welcome",
    availabilityText: "Join us this Sunday",
  },

  school: {
    name: "School / Education",
    searchTerms: [
      "school near me",
      "private school",
      "charter school",
      "preschool near me",
      "tutoring center",
      "after school programs",
      "education center",
    ],
    avgTicket: { service: 0, install: 12000 },
    conversionRate: 0.05,
    closeRate: 0.4,
    gbpCategory: "School",
    defaultServices: [
      { name: "K-12 Education", icon: "📚", desc: "Comprehensive academic programs from kindergarten through 12th grade." },
      { name: "Early Childhood", icon: "🎨", desc: "Preschool and pre-K programs that build a strong foundation." },
      { name: "After-School Programs", icon: "🏫", desc: "Enrichment, tutoring, and supervised activities after school." },
      { name: "Athletics & Activities", icon: "⚽", desc: "Sports teams, clubs, and extracurricular activities." },
      { name: "Special Programs", icon: "🌟", desc: "STEM, arts, advanced placement, and specialized learning." },
      { name: "Summer Programs", icon: "☀️", desc: "Summer camps, academic enrichment, and skill-building programs." },
    ],
    whyChoose: [
      { title: "Academic Excellence", desc: "Proven track record of student achievement." },
      { title: "Dedicated Faculty", desc: "Experienced, caring teachers committed to every student." },
      { title: "Safe Environment", desc: "Secure campus with a focus on student wellbeing." },
      { title: "Community Values", desc: "Building character alongside academic skills." },
    ],
    warrantyText: "Enrollment Open",
    badgeText: "Now Enrolling",
    availabilityText: "Schedule a tour today",
  },

  local_government: {
    name: "Local Government",
    searchTerms: [
      "town hall",
      "city government",
      "municipal services",
      "village hall",
      "county office",
      "public services",
      "town clerk",
    ],
    avgTicket: { service: 0, install: 0 },
    conversionRate: 0.03,
    closeRate: 0.2,
    gbpCategory: "Government office",
    defaultServices: [
      { name: "Permits & Licensing", icon: "📋", desc: "Building permits, business licenses, and regulatory approvals." },
      { name: "Public Works", icon: "🚧", desc: "Roads, water, sewer, and infrastructure maintenance." },
      { name: "Parks & Recreation", icon: "🌳", desc: "Public parks, recreation programs, and community facilities." },
      { name: "Public Safety", icon: "🛡️", desc: "Police, fire, and emergency management services." },
      { name: "Community Programs", icon: "🏛️", desc: "Senior services, youth programs, and community events." },
      { name: "Tax & Assessment", icon: "💰", desc: "Property tax information, assessments, and payment services." },
    ],
    whyChoose: [
      { title: "Transparent Governance", desc: "Open meetings, public records, and community engagement." },
      { title: "Responsive Service", desc: "Dedicated staff serving residents and businesses." },
      { title: "Community Investment", desc: "Investing in infrastructure, safety, and quality of life." },
      { title: "Accessible Information", desc: "Online services and up-to-date community resources." },
    ],
    warrantyText: "Serving Our Community",
    badgeText: "Public Service",
    availabilityText: "Office hours: Mon-Fri 9am-5pm",
  },
};
